services:
  postgres:
    image: postgres:15
    container_name: postgresDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d restaurant']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_server
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_CONNECT: ${DB_CONNECT}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
